theme: jekyll-theme-leap-day
title: jc98w ePortfolio
show_downloads: true
description: CS 499 ePortfolio

nav-pages:
  - page-title: Introduction
    url: "/"
  - page-title: "Code Review"
    url: "/code_review.html"
  - page-title: "Enhancement One"
    url: "/enhancement_one.html"
  - page-title: "Enhancement Two"
    url: "/enhancement_two.html"
  - page-title: "Enhancement Three"
    url: "/enhancement_three.html"