theme: jekyll-theme-leap-day
title: jc98w ePortfolio
description: CS 499 ePortfolio

nav-pages:
  - title: intro
    url: "/"
  - title: code_review
    url: "/code_review.html"
  - title: enhancement_one
    url: "/enhancement_one.html"
  - title: enhancement_two
    url: "/enhancement_two.html"
  - title: enhancement_three
    url: "/enhancement_three.html"